version: 2.0

id: "telus-standard"

about:
  title: "telus-standard"
  description: Standard linting rules for TELUS Digital

contacts:
  - type: Project Owner
    name: Stephen Marie-Rhodes
    email: Stephen.Marie-Rhodes@telus.com
    github: stepmr
  - type: Developer
    name: Matthew Cantelon
    email: matthew.cantelon@telus.com
    github: mattcan

references:
  - title: NPM Package
    uri: https://www.npmjs.com/package/@telus/telus-standard

environments:
  - title: Source Code
    uri: https://github.com/telus/telus-standard.git
